### PR TITLE
Further revision, including USE

### PR DESCRIPTION
**Pull request by lucyrpedro**

### CODE REVIEW

**Review by JulianKunkel — COMMENTED** [review]
I can't see any significant changes here, except whitespace? Is there something missing?

**Comment by lucyrpedro** [comment]
Dear Julian.

I'm no Git expert, but there are 17 commits here. Don't you see anything different, at all?

One thing that changed is that you modified the sync time for the webpage auto-commit, which has caused some conflicts for me (it used to be once a day, at 3 am). As I mentioned in my email, most of the changes I did yesterday where directly in the wiki because I was revising Saturday's work and checking spelling and grammar (which is easier in the browser). I also finished the revision of USE.

You need to tell me something more specific so I can give you a precise answer.

Kind regards.

Luciana.

**Review by lucyrpedro — COMMENTED** [review]
This one, for instance, happens just when I open/close some files. I mentioned that before. I explored the issue on Google and it's a GIT situation that I don't want to solve anymore. I spent maybe three hours trying to solve it and I've given up.

**Review by lucyrpedro — COMMENTED** [review]
Here you can see the conflicts I mentioned.

**Comment by JulianKunkel** [comment]
Basically, you can see here:
https://github.com/HPC-certification-forum/skill-tree/pull/7/files

I merged the squashed version to get rid of your conflicts. The sync is now every hour...

**Pull request merged**
